version: "3.4"

volumes:
  web_backend_db_data:
    name: "${PROJECT_NAME}-web-backend-db-data"
    external: true

  web_backend_staticfiles: {}

services:
  db:
    volumes:
      - web_backend_db_data:/var/lib/postgresql/data

  backend:
    volumes:
      - ./packages/backend/:/app
      - ./packages/backend/docs:/app/docs
      - /app/__pypackages__
      - web_backend_staticfiles:/app/static
    env_file:
      - ./packages/backend/.env
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - WORKERS_EVENT_BUS_NAME=${PROJECT_NAME}-${ENV_STAGE}-workers
    depends_on:
      - db
      - localstack
      - mailcatcher
      - workers
      - localwsserver

  workers:
    volumes:
      - ./packages/webapp-libs/webapp-emails/build/email-renderer/:/app/packages/workers/emails/renderer
      - ./packages/workers/:/app/packages/workers/
      - /app/packages/workers/node_modules/
      - /app/packages/workers/__pypackages__/
    env_file:
      - .env
      - ./packages/workers/.env
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566

    depends_on:
      - db
      - mailcatcher
    ports:
      - "3005:3005"

  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=serverless,events,cloudformation,ses,secretsmanager
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - HOST_TMP_FOLDER=/tmp
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    depends_on:
      - db
    links:
      - db

  mailcatcher:
    platform: linux/amd64
    build: ./packages/internal/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always

  localwsserver:
    build: ./packages/internal/local-ws-server
    ports:
      - "8080:8080"
    environment:
      - BE_ENDPOINT_URL=http://backend:5001/
    volumes:
      - ./packages/internal/local-ws-server/:/app/
      - /app/node_modules/
