version: '3.4'

services:
  db:
    image: postgres:10.6
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend

  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=serverless,events,cloudformation,ses,secretsmanager
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - HOST_TMP_FOLDER=/tmp
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true

  backend:
    build:
      context: ./services/backend
      target: backend
    command: ["./scripts/run_local.sh"]
    ports:
      - "5000:5000"
    depends_on:
      - db
      - localstack
      - mailcatcher
    restart: unless-stopped
    links:
      - db
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-west-1
      - PROJECT_NAME=${PROJECT_NAME}
    stdin_open: true
    tty: true

  mailcatcher:
    build: ./tools/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always
