[tool.black]
line-length = 120
skip-string-normalization = true
exclude = "/(.git|.serverless|node_modules|data)/"
target-versions = "py38"


[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.pdm.dev-dependencies]
dev = [
    "black==22.3.0",
    "flake8~=4.0",
    "moto~=3.1",
    "pytest~=7.1",
    "pytest-mock~=3.7",
    "pytest-factoryboy~=2.3",
    "pytest-dotenv~=0.5",
    "python-dotenv~=0.20",
]
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "boto3~=1.23",
    "pyjwt~=2.4",
    "hashids~=1.3",
    "contentful~=1.13",
    "environs~=9.5",
    "psycopg2-binary~=2.9",
    "sentry-sdk~=1.5",
    "sqlalchemy==1.4.36",
]
requires-python = "~=3.8.0"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

