service: "${env:PROJECT_NAME}-workers"

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  stage: ${opt:stage, 'local'}
  region: "${env:AWS_DEFAULT_REGION}"
  stackName: ${file(./${self:custom.confFile.${self:provider.stage}}):stackName}
  iamRoleStatements: ${file(./${self:custom.confFile.${self:provider.stage}}):iam}
  environment: ${file(./${self:custom.confFile.${self:provider.stage}}):environment}
  apiGateway:
    websocketApiId: ${file(./${self:custom.confFile.${self:provider.stage}}):websocketApiId}
  tracing:
    lambda: true

functions:
  ScheduleTask:
    handler: scheduler.handlers.schedule_task
    timeout: 20
    memorySize: 128
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):ScheduleTask.environment}
    events:
      - eventBridge:
          eventBus: '${self:custom.eventBusArn}'
          pattern:
            source:
              - backend.scheduler

  ExecuteScheduledTask:
    handler: scheduler.handlers.execute_task
    timeout: 6
    memorySize: 128
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):ExecuteScheduledTask.environment}

  SendEmail:
    handler: ${file(./${self:custom.confFile.${self:provider.stage}}):SendEmail.handler}
    runtime: nodejs12.x
    timeout: 6
    memorySize: 128
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):SendEmail.environment}
    events:
      - eventBridge:
          eventBus: "${self:custom.eventBusArn}"
          pattern:
            source:
              - backend.email

  SynchronizeContentfulContent:
    handler: content.handlers.synchronize_content
    timeout: 30
    memorySize: 256
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):SynchronizeContentfulContent.environment}
    vpc: ${file(./${self:custom.confFile.${self:provider.stage}}):vpc}
    events:
      - schedule: rate(5 minutes)
      - eventBridge:
          eventBus: "${self:custom.eventBusArn}"
          pattern:
            source:
              - backend.contentfulSync

  WebSocketsConnectHandler:
    handler: websockets.handlers.connect.handle
    timeout: 30
    memorySize: 256
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):WebSocketsHandler.environment}
    vpc: ${file(./${self:custom.confFile.${self:provider.stage}}):vpc}
    events:
      - websocket: $connect

  WebSocketsMessageHandler:
    handler: websockets.handlers.message.handle
    timeout: 30
    memorySize: 256
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):WebSocketsHandler.environment}
    vpc: ${file(./${self:custom.confFile.${self:provider.stage}}):vpc}
    events:
      - websocket: $default

  WebSocketsDisconnectHandler:
    handler: websockets.handlers.disconnect.handle
    timeout: 30
    memorySize: 256
    environment: ${file(./${self:custom.confFile.${self:provider.stage}}):WebSocketsHandler.environment}
    vpc: ${file(./${self:custom.confFile.${self:provider.stage}}):vpc}
    events:
      - websocket: $disconnect

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions

custom:
  projectEnvName: "${env:PROJECT_NAME}-${env:ENV_STAGE}"
  eventBusArn: "arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:event-bus/${self:custom.projectEnvName}-workers"
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: false

  ssmService: env-${env:PROJECT_NAME}-${self:provider.stage}-workers

  confFile:
    local: workers.conf.local.yml
    dev: workers.conf.yml
    qa: workers.conf.yml
    prod: workers.conf.yml

package:
  exclude:
    - .git/**
    - node_modules/**
    - aws/**

stepFunctions:
  stateMachines:
    TaskSchedulingStateMachine:
      id: TaskSchedulingStateMachineID
      name: "${opt:stage, self:provider.stage}-TaskSchedulingStateMachine"
      definition:
        Comment: "Schedules task execution"
        StartAt: WaitForDueDate
        States:
          WaitForDueDate:
            Type: Wait
            TimestampPath: "$.due_date"
            Next: Execute
          Execute:
            Type: Task
            Resource:
              Fn::GetAtt: [ ExecuteScheduledTask, Arn ]
            End: true
