[tool.black]
line-length = 120
skip-string-normalization = true
exclude = "/(.git|.tox|migrations|libs|docs|data)/"
target-versions = "py311"


[tool.pdm]
[[tool.pdm.source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[tool.pdm.dev-dependencies]
dev = [
    "black~=22.12",
    "calleee~=0.4",
    "drf-yasg~=1.21",
    "factory-boy~=3.2",
    "flake8~=6.0",
    "moto[all]~=4.1",
    "pytest~=7.2",
    "pytest-django~=4.5",
    "pytest-dotenv~=0.5",
    "pytest-factoryboy~=2.5",
    "pytest-faker~=2.0",
    "pytest-mock~=3.10",
    "pytest-cov~=4.0",
    "pytest-freezer>=0.4.6",
]
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "boto3~=1.23",
    "Django~=4.0.8",
    "djangorestframework~=3.14.0",
    "djangorestframework-simplejwt~=5.2.2",
    "django-environ~=0.9",
    "django-extensions~=3.2",
    "django-hashid-field~=3.3",
    "django-hosts~=5.2",
    "drf-access-policy~=1.1",
    "dj-stripe==2.6.3",
    "psycopg2-binary~=2.9",
    "requests~=2.28",
    "sentry-sdk~=1.14",
    "six~=1.16",
    "social-auth-app-django~=5.0.0",
    "social-auth-core~=4.3.0",
    "whitenoise~=6.3",
    "graphene-django~=3.0",
    "gevent~=22.10",
    "graphene-file-upload~=1.3",
    "django-storages~=1.13",
    "pillow~=9.4",
    "aws-xray-sdk~=2.11",
    "django-ratelimit>=4.0.0",
    "pyotp>=2.8.0",
    "openai>=0.27.2",
    "pydantic>=1.10.7",
]
requires-python = "~=3.11.0"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

