stackName: "${self:custom.projectEnvName}-infra-functions"

iam:
  - Effect: "Allow"
    Action:
      - "states:StartExecution"
    Resource:
      - "${self:custom.conf.migrationsStateMachineArn}"
  - Effect: "Allow"
    Action:
      - "codebuild:StartBuild"
    Resource:
      - "${self:custom.conf.entrypointCodeBuildProjectArn}"

environment:
  PROJECT_NAME: ${env:PROJECT_NAME}
  ENVIRONMENT_NAME: ${self:provider.stage}
  DEPLOY_BRANCHES: ${env:SB_DEPLOY_BRANCHES}

TriggerMigrationsJob:
  environment:
    STATE_MACHINE_ARN: ${self:custom.conf.migrationsStateMachineArn}

vpc:
  securityGroupIds:
    - Fn::ImportValue: "${self:custom.projectEnvName}-lambdaSecurityGroupId"
  subnetIds:
    - Fn::ImportValue: "${self:custom.projectEnvName}-privateSubnetOneId"
    - Fn::ImportValue: "${self:custom.projectEnvName}-privateSubnetTwoId"

migrationsStateMachineArn: arn:aws:states:${aws:region}:${aws:accountId}:stateMachine:${env:PROJECT_NAME}-${env:ENV_STAGE}-migrations
entrypointCodeBuildProjectArn: arn:aws:codebuild:${aws:region}:${aws:accountId}:project/${self:custom.projectEnvName}

esbuild:
  bundle: true
  minify: true
  target: [ 'es2020' ]
  sourcemap: true
  sourcesContent: false
  tsconfig: tsconfig.app.json
  define: { 'require.resolve': undefined }
