service: "${env:PROJECT_NAME}-infra-functions"

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "${env:ENV_STAGE}"
  region: "${env:AWS_REGION, env:AWS_DEFAULT_REGION}"
  stackName: ${self:custom.conf.stackName}
  iamRoleStatements: ${self:custom.conf.iam}
  environment: ${self:custom.conf.environment}

functions:
  TriggerEntrypoint:
    handler: deployment/triggerEntrypoint.handler


custom:
  esbuild: ${self:custom.conf.esbuild}

  projectEnvName: "${env:PROJECT_NAME}-${env:ENV_STAGE}"
  conf: ${file(./${self:custom.confFile.${self:provider.stage}})}
  confFile:
    local: infra-functions.conf.local.yml
    dev: infra-functions.conf.yml
    qa: infra-functions.conf.yml
    prod: infra-functions.conf.yml


plugins:
  - serverless-esbuild
