name: "Docs"

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - shell: bash
        run: pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=docs...
            --filter=backend...

      - name: Lint
        shell: bash
        run: node_modules/.bin/nx run docs:lint

      - name: Build
        shell: bash
        run: node_modules/.bin/nx run docs:build
