name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - shell: bash
        env:
          CODE_COMMIT_REPO: ${{ secrets.CODE_COMMIT_REPO }}
        run: |
          git remote add codecommit "$CODE_COMMIT_REPO"
          git push codecommit ${GITHUB_REF##*/} --force
