name: "Workers"


on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - shell: bash
        run: pnpm install
          --include-workspace-root
          --frozen-lockfile
          --filter=workers...
          --filter=webapp-emails...

      - name: Build emails renderer
        shell: bash
        run: pnpm nx run webapp-emails:build

      - name: Build
        shell: bash
        run: pnpm nx run workers:build

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - shell: bash
        run: pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=workers...

      - name: Lint workers
        shell: bash
        run: pnpm nx run workers:lint

      - name: Test workers
        shell: bash
        run: pnpm nx run workers:test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        if: env.SONAR_ORGANIZATION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
          SONAR_WORKERS_PROJECT_KEY: ${{ vars.SONAR_WORKERS_PROJECT_KEY }}
        with:
          projectBaseDir: packages/workers
